services:
  - type: web
    name: discord-user-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api.main:app"
    envVars:
      - key: PORT
        value: 10000
