services:
  - type: web
    name: ratistan-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn rat.wsgi:application"
    envVars:
      - key: PORT
        value: 10000
