services:
  - type: web
    name: discord-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn rat.wsgi:application"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
